apiVersion: apps/v1beta2
kind: Deployment
metadata:
   name: dockersampling
spec:
   replicas: 2
   selector:
      matchLabels:
         app: dockersampling 
   minReadySeconds: 100
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 1
         maxSurge: 1
   template:
      metadata:
         labels:
            app: dockersampling
      spec:
         containers:
         - name: dockersampler
           image: eswaribala/ecommercerepo:ecommtag
           ports:
           - containerPort: 7070
           imagePullPolicy: Always 
             